version: "3.3"
services:
  order-broker:
    image: ${REGISTRY}:order-broker
    build:
      args:
        - ENV=${ENV}
        - SERVER_PORT=${SERVER_PORT}
      context: ../
      dockerfile: ./order-broker/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - ENV=${ENV}
      - SERVER_PORT=${SERVER_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - SENTRY_DSN=${SENTRY_DSN}
      - NATS_SERVERS=${NATS_SERVERS}
    deploy:
      replicas: 1
    volumes:
      - ./:${VOLUME_PATH}
    working_dir: /opt/order-broker
    command: npm run start:prod
