#!/bin/bash
set -e

[[ -d /dev/net ]] ||
    mkdir -p /dev/net
[[ -c /dev/net/tun ]] ||
    mknod /dev/net/tun c 10 200

cd /etc/openvpn

[[ -f dh.pem ]] ||
    openssl dhparam -out dh.pem 1024
[[ -f key.pem ]] ||
    openssl genrsa -out key.pem 2048
chmod 600 key.pem
[[ -f csr.pem ]] ||
    openssl req -new -key key.pem -out csr.pem -subj /CN=OpenVPN/
[[ -f cert.pem ]] ||
    openssl x509 -req -in csr.pem -out cert.pem -signkey key.pem -days 24855

export PUBLIC_IP=$(curl http://169.254.169.254/2009-04-04/meta-data/public-ipv4)

cat >udp1194.conf <<EOF
server 192.168.255.128 255.255.255.128
verb 3
duplicate-cn
key key.pem
ca cert.pem
cert cert.pem
dh dh.pem
keepalive 10 60
persist-key
persist-tun
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
push "route 10.40.0.0 255.255.0.0"

proto udp
port 1194
dev tun1194
status openvpn-status-1194.log
EOF

cat >client.ovpn <<EOF
client
nobind
dev tun
route 10.40.0.0 255.255.0.0


<key>
`cat key.pem`
</key>
<cert>
`cat cert.pem`
</cert>
<ca>
`cat cert.pem`
</ca>
<dh>
`cat dh.pem`
</dh>

<connection>
remote $PUBLIC_IP 1194 udp
</connection>

EOF

iptables -t nat -A POSTROUTING -s 192.168.255.0/24 -o eth0 -j MASQUERADE

touch udp1194.log
while true ; do openvpn udp1194.conf ; done >> udp1194.log &
tail -F udp1194.log
