---
- import_playbook: nats_build.yml
  when: build is defined and build == 'true'

- import_playbook: nats_stream_console_build.yml
  when: build is defined and build == 'true'

- name: Install NATS streaming server
  vars_files:
    - "../config/{{ env }}.yml"
  become: yes
  hosts: "{{ env }}[0]"
  tasks:
    - name: Deploy NATS
      docker_swarm_service:
        name: nats
        image: "rhaziel/nats"
        force_update: true
        args:
          - "--store"
          - "file"
          - "--dir"
          - "/data"
          - "--cluster_id"
          - "jackal-cluster"
          - "--max_age"
          - "60m"
          - "--max_inactivity"
          - "60m"
          - "--http_port"
          - "8222"
          - "--config"
          - "/opt/nats/nats-server.conf"
        networks: main
        user: null

    - name: Deploy NATS Streaming Console [deploy stack]
      docker_swarm_service:
        name: nats-streaming-console
        image: "rhaziel/nats-streaming-console"
        force_update: true
        command: node server
        publish:
          - published_port: 8282
            target_port: 8282
        env:
          - "STAN_CLUSTER=jackal-cluster"
          - "STAN_URL=nats://nats:4222"
          - "STAN_MONITOR_URL=http://nats:8222"
        networks: main
        user: null
