---

- name: Update local NPM registry
  hosts: localhost
#  become: true
  vars:
    first_host: "{{ groups[env][0] }}"
  vars_files:
    - "../config/{{ env }}.yml"

  tasks:
    - name: Add user to npm private registry
      shell: |
        /usr/bin/expect <<EOD
        spawn npm adduser --registry=http://npm.registry.hypercentage.com --scope=@hypercentage
        expect {
          "Username:" {send "{{ npm.user }}\r"; exp_continue}
          "Password:" {send "{{ npm.password }}\r"; exp_continue}
          "Email: (this IS public)" {send "{{ npm.email }}\r"; exp_continue}
        }
        EOD
      when: env_name == 'dev'

    - name: Use this only in dev mode
      shell: |
        echo "Use it with Dev env"
      when: env_name != 'dev'
