version: '3'
services:
  grafana:
    image: grafana/grafana:6.3.6
    ports:
      - "4000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,goshposh-metaqueries-datasource
      - GF_SERVER_DOMAIN=pandora.hypercentage.com
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_NAME=Hypercentage
      - GF_SECURITY_ALLOW_EMBEDDING=true
#      - GF_AUTH_GOOGLE_ENABLED=true
#      - GF_AUTH_GOOGLE_ALLOW_SIGN_UP=true
#      - GF_AUTH_GOOGLE_CLIENT_ID=115434256667-f00030014e874bpiocen29obg2qb1jd4.apps.googleusercontent.com
#      - GF_AUTH_GOOGLE_CLIENT_SECRET=n3P8-eDfCUa7LxSvecmaYWPt
#      - GF_AUTH_GOOGLE_SCOPES=https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
#      - GF_AUTH_GOOGLE_AUTH_URL=https://accounts.google.com/o/oauth2/auth
#      - GF_AUTH_GOOGLE_TOKEN_URL=https://accounts.google.com/o/oauth2/token
#      - GF_AUTH_GOOGLE_API_URL=https://www.googleapis.com/oauth2/v1/userinfo
#      - GF_AUTH_GOOGLE_ALLOWED_DOMAINS='keyzone-group.com hypercentage.com lenodo.net relario.com forsageholdings.com'

    entrypoint:
      - /run.sh
      - cfg:default.database.type=mysql
      - cfg:default.domain=pandora.hypercentage.com
      - cfg:default.server.root_url=%(protocol)s://%(domain)s/grafana/
      - cfg:default.database.host={{ db.host }}
      - cfg:default.database.name={{ db.name }}
      - cfg:default.database.user={{ db.user }}
      - cfg:default.database.password={{ db.password }}
    networks:
      - main

networks:
  main:
    external:
      name: main


